name: Flutter Web - Push
on:
  push:
    branches:
      - development
      - homologation
      - main
jobs:
  deploy:
    name: Update
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'pro' || github.ref == 'refs/heads/homologation' && 'hom' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Checkout Bitbucket Repository
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BITBUCKET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3 # path to pubspec.yaml
      - run: flutter --version
      - run: rm -rf build/
      - run: flutter pub get
      - run: flutter build web --release --web-renderer canvaskit -t ${{vars.MAIN_FILE}}
      - run: aws s3 sync build/web/ s3://${{vars.S3_BUCKET}}/ --delete  # Sincronizar arquivos no S3 para desenvolvimento
      - run: aws cloudfront create-invalidation --distribution-id ${{vars.CLOUD_FRONT_DISTRIBUTION_ID}} --paths "/*"  # Invalidação no CloudFront
